Update include/openmc/nuclide.h
The Intel LLVM compiler fails to compile 'nuclide.cpp' with error

  error: use of undeclared identifier 'model'

This patch adds the missing include to 'nuclide.h'.