Add missing ifp.h include to particle.cpp
Include openmc/ifp.h to resolve undefined reference to
is_beta_effective_or_both() function. This function is used
when initializing the lineage flag for kinetics calculations
with IFP mode enabled.

Fixes compilation error:
  error: 'is_beta_effective_or_both' was not declared in this scope